# Generated by Django 2.2.5 on 2019-09-22 18:37

from django.db import migrations
import django.utils.timezone
import mdeditor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='content',
        ),
        migrations.AddField(
            model_name='post',
            name='body',
            field=mdeditor.fields.MDTextField(default=django.utils.timezone.now, verbose_name='正文'),
            preserve_default=False,
        ),
    ]
